### ISSUE TITLE
 vaultfixes-3.13-1.0.3.jar needs language provider kotlinforforge:3

### ISSUE THREAD

**Issue by Hjard** [CanadianKoruko/VaultFixes#1]
Just tried putting the vault fixes mod on our server and it prevented the server from loading. Was on a fresh instance with only starlight, lazyDFU, worldedit and smoothchunk added so nothing that should cause the issue described in the crash report.

Server is provided by Gravelhost but to my knowledge they don't do anything to modify the game instance either.
[crash-2024-02-11_02.57.19-fml.txt](https://github.com/CanadianKoruko/VaultFixes/files/14231889/crash-2024-02-11_02.57.19-fml.txt)

**Comment by KoromaruKoruko** [comment]
Please install all dependencies on a vault hunters server.

You are missing kotlinforforge

**Comment by KoromaruKoruko** [comment]
You can reopen this if there are any actual issues.

Please don't make issues that answer themselves in the title
